name: Deploy Foundary VTT cfn
run-name: ${{ github.actor }} is applying Foundary template
on: [push]
permissions:
  id-token: write
jobs:
  Test-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t ./cloudformation/foundary.yml

  Deploy-template:
    needs: Test-template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: MyFoundaryStack
          template: ./cloudformation/foundary.yaml